name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  Publish:
    name: Publish Workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ecosystem-sdk/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ecosystem-sdk/sdk/.nvmrc
          cache: 'yarn'
          cache-dependency-path: ecosystem-sdk/sdk/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Configure npm for Authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}